@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDU4OTk5NTd9.P6G20JbdVAOssxzhdrvU3MEntdP0tK6wMh67r1i8vks

@domain = http://localhost:3000

POST {{ domain }}/equipment-sets
Content-Type: application/json

{
  "name": "test name",
  "items": [
    {
      "id": 2,
      "slot": "2h"
    },
    {
      "id": 4151,
      "slot": "2h"
    }
  ]
}

###Update EquipmentSet
PATCH {{ domain }}/equipment-sets/1
Content-Type: application/json

{
  "items": [
    {
      "id": 2,
      "slot": "legs"
    },
    {
      "id": 3,
      "slot": "chest"
    },
    {
      "id": 4,
      "slot": "head"
    },
    {
      "id": 5,
      "slot": "bracers"
    },
    {
      "id": 4151,
      "slot": "2h"
    }
  ]
}

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "display_name": "kevin bcrypt",
  "email": "kevin@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "kevin@test.com",
  "password": "password"
}