POST http://localhost:3000/equipment-sets
Content-Type: application/json

{
  "name": "test name",
  "items": [
    {
      "id": 2,
      "slot": "2h"
    },
    {
      "id": 4151,
      "slot": "2h"
    }
  ]
}

###Update EquipmentSet
PATCH http://localhost:3000/equipment-sets/1
Content-Type: application/json

{
  "items": [
    {
      "id": 2,
      "slot": "legs"
    },
    {
      "id": 3,
      "slot": "chest"
    },
    {
      "id": 4,
      "slot": "head"
    },
    {
      "id": 5,
      "slot": "bracers"
    },
    {
      "id": 4151,
      "slot": "2h"
    }
  ]
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "display_name": "kevin bcrypt",
  "email": "kevin@test.com",
  "password": "password",
  "password_confirmation": "password"
}